---
title: "Untitled"
author: "郑元瑞"
date: "`r Sys.Date()`"
output: html_document
---
# Sample size determination
## import packages and data preprocessing
### import packages
```{r}
rm(list = ls())#clear the environment
###############import the packages##############
library(tidyverse)
library(showtext)
library(here)
library(BayesFactor)
showtext.auto()
#set the path#
file_path <- here("5_Data", "exp1_osf_data")
#change working directory
bruceR::set.wd()
source('./utils.R')
```
### import data
```{r, include=F}
files <- list.files(file_path, pattern = "csv", full.names = TRUE, recursive =T)
all <- purrr::map_dfr(.x = files, .f = ~jspsycsv2df(.x))
```

### data preprocessing
```{r}
# all <- all %>% 
#   mutate_at(vars(word,valence), function(x){iconv(x, from = "GBK", to = "UTF-8")})
data <- all %>% #exclude practice
  dplyr::filter(exp_condition == "Formal")
##################################
# this is unnecessary for the true data!
# nrow(data)/3
# data[1:720,]$subj_idx <- '2'
# data[721:1440,]$subj_idx <- '3'
##################################
data2 <- data %>% 
  dplyr::filter(rt != "null")
data2$rt <- as.numeric(data2$rt)/1000
data2 = data2 |> mutate(
  target_identity = if_else(target == "Word", word, valence), # first stimulus
  test_identity = if_else(target == "Word", valence, word), # second stimulus
)
data2 = data2 |> mutate(ACC = as.numeric(correct))

df.agg1 <- data2 %>% 
  dplyr::group_by(subj_idx, target, valence, matchness) %>% 
  dplyr::summarise(rt_mean = mean(rt), 
            sd = sd(rt)) %>% 
  dplyr::ungroup()

```
## Sequential Bayes factor Analysis
### rmANOVA and paired t-test

```{r}
df.agg1$subj_idx <- as.factor(df.agg1$subj_idx)

subjects1 <- sort(unique(df.agg1$subj_idx)) # sort by subjects' id

subjects1

stages <- c(seq(4, 12, by = 2)) # In the first stage we collected 20 subjects, and the second stage we collected 10 subjects

stage_n1 <- 0 # setting for count the loop times

bfdf1 <- data.frame(effect = NA, N = NA, BF = NA, stage = NA, upper_threshold = NA, lower_threshold = NA) # initial a dataframe to store results

for (i in stages) {
  # selected the data by subjects in each stage
  data1 <- subset(df.agg1, subj_idx %in% head(subjects1, i))

  stage_n1 <- stage_n1 + 1 # starting to add the loop times

  message(length(unique(data1$subj_idx)), " subjects")

  message("The data collection stage is ", stage_n1)

  data1$subj_idx <- as.factor(data1$subj_idx) # to factor

  bayesfactors1 <- BayesFactor::generalTestBF(
    rt_mean ~ valence * matchness * target * subj_idx - subj_idx:valence:matchness:target,# exclude the highest random effect
    data = data.frame(data1),
    whichRandom = "subj_idx",
    neverExclude = "subj_idx",
    whichModels = "top"
  )

  summary(bayesfactors1)

  gc()
  data1_match <- data1 %>% 
  dplyr::filter(matchness == "Match")# filter the match condition
  data_match_self <- data1_match %>% 
    dplyr::filter(valence == "自我")# filter self condition in match condition
  data_match_other <- data1_match %>% 
    dplyr::filter(valence == "他人")#filter other
  
  data1_self <- data1 %>% 
  dplyr::filter(valence == "自我")#filter self condition
  data_self_word <- data1_self %>% 
    dplyr::filter(target == "Word")#filter word condition in self condition
  data_self_Image <- data1_self %>% 
    dplyr::filter(target == "Image")
  
  message(sum(data_match_self$target == data_match_other$target), " conditions matching")# check if other condition is matching
  
  message(sum(data_self_word$matchness == data_self_Image$matchness), " conditions matching")#check
  
  self_other_m <- BayesFactor::ttestBF(x=data_match_self$rt_mean,
                                       y=data_match_other$rt_mean, paired = TRUE)# paired t test 
  word_image_m <- BayesFactor::ttestBF(x=data_self_word$rt_mean, y=data_self_Image$rt_mean, paired = TRUE)

  
  self_other_output <- as.data.frame(self_other_m)[1,1]
  word_image_output <- as.data.frame(word_image_m)[1,1]
  
  bf_bo_match <- data.frame(
    effect = "Match_self-Match_other", N = i,
    BF = self_other_output, stage = stage_n1,
    upper_threshold = 10, lower_threshold = 1 / 10
  )
  
  bf_iw_self <- data.frame(
  effect = "Self_Image-Self_Word", N = i,
  BF = word_image_output, stage = stage_n1,
  upper_threshold = 10, lower_threshold = 1 / 10
)

  df_output1 <- as.data.frame(bayesfactors1) # restore the information of result

  # setting the matchness:target:valence effect threshold of the BF to 10,1/10
  bf_3wayinx1 <- data.frame(
    effect = "matchness:target:valence", N = i,
    BF = 1 / df_output1[1, 1], stage = stage_n1,
    upper_threshold = 10, lower_threshold = 1 / 10
  )

  # setting the matchness:target:valence effect threshold of the BF to 6,1/6
  bf_mtinx1 <- data.frame(
    effect = "matchness:target", N = i,
    BF = 1 / df_output1[2, 1], stage = stage_n1,
    upper_threshold = 6, lower_threshold = 1 / 6
  )


  bf_tvinx1 <- data.frame(
    effect = "target:valence", N = i,
    BF = 1 / df_output1[3, 1], stage = stage_n1,
    upper_threshold = 6, lower_threshold = 1 / 6
  )


  bf_mvinx1 <- data.frame(
    effect = "matchness:valence", N = i,
    BF = 1 / df_output1[4, 1], stage = stage_n1,
    upper_threshold = 6, lower_threshold = 1 / 6
  )

  # setting the BF threshold of main effect of target to 10,1/10
  bf_tmain1 <- data.frame(
    effect = "target", N = i,
    BF = 1 / df_output1[5, 1], stage = stage_n1,
    upper_threshold = 10, lower_threshold = 1 / 10
  )


  bfdf1 <- rbind(bfdf1, bf_3wayinx1, bf_mtinx1, bf_tvinx1, bf_mvinx1, bf_tmain1, 
                 bf_bo_match, bf_iw_self)
}


```
```{r}
bfdf1 %>% 
  drop_na() %>% 
  ggplot(aes(x=N, y=BF)) +
  geom_hline(aes(yintercept = upper_threshold), color = 'red') + 
  geom_hline(aes(yintercept = lower_threshold), color = 'blue') + 
  geom_line() + 
  geom_point() + 
  facet_wrap(~effect, scales = "free_y")
```

```{r}
data2 |> papaja::apa_barplot(
  id = "subj_idx",
  factors = c("target", "matchness"),
  dv = "rt"
)

data2 |> papaja::apa_barplot(
  id = "subj_idx",
  factors = c("target", "matchness"),
  dv = "correct"
)

```

```{r}
data2 |> papaja::apa_barplot(
  id = "subj_idx",
  factors = c("matchness", "valence"),
  dv = "rt"
)

data2 |> papaja::apa_barplot(
  id = "subj_idx",
  factors = c("matchness", "word"),
  dv = "rt"
)

data2 |> papaja::apa_barplot(
  id = "subj_idx",
  factors = c("matchness", "prime_identity"),
  dv = "rt"
)
```
```{r}
data2 |> papaja::apa_barplot(
  id = "subj_idx",
  factors = c("matchness", "valence"),
  dv = "correct"
)

data2 |> papaja::apa_barplot(
  id = "subj_idx",
  factors = c("matchness", "word"),
  dv = "correct"
)

data2 |> papaja::apa_barplot(
  id = "subj_idx",
  factors = c("matchness", "prime_identity"),
  dv = "correct"
)
```

```{r}

data2 |> papaja::apa_barplot(
  id = "subj_idx",
  factors = c("target", "valence"),
  dv = "rt"
)

data2 |> papaja::apa_barplot(
  id = "subj_idx",
  factors = c("target", "word"),
  dv = "rt"
)

data2 |> papaja::apa_barplot(
  id = "subj_idx",
  factors = c("target", "target_identity"),
  dv = "rt"
)

data2 |> papaja::apa_barplot(
  id = "subj_idx",
  factors = c("target", "test_identity"),
  dv = "rt"
)
```
```{r}
data2 |> papaja::apa_barplot(
  id = "subj_idx",
  factors = c("matchness", "target"),
  dv = "rt"
)
```

```{r}
cbp <- ggokabeito::palette_okabe_ito(c(1,2,7,3,5,6,4))

# theme
theme_set(
  papaja::theme_apa(base_size = 14, base_family = "serif")
)

aa = lifetable_group_by(data2, subj_idx, matchness, target)
 
fig_hf = plot_EHA(aa, "hf", title = "hazard function")
fig_caf = plot_EHA(aa, "caf", title = "accuracy conditional function")
fig_pdf = plot_EHA(aa, "pdf", title = "pdf")
fig_cdf = plot_EHA(aa, "cdf", title = "cdf")

library(ggpubr)
fig_EHA = ggarrange(
  fig_hf, fig_pdf, fig_caf, fig_cdf, 
  labels = c("A", "B", "C", "D"),
  common.legend = T, legend = "right",
  font.label = list(size = 13, face = "bold"))

ggsave("Figs/figs_EHA_test.tiff", fig_EHA,
       width = 9, height = 6, bg = "white",
       dpi = 300, compression = "lzw")


summary(data2$rt)


```

